# Generated by Django 6.0.4 on 2026-05-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
